### ISSUE TITLE
Error compiling on 0.2.2

### ISSUE THREAD

**Issue by twastvedt** [barbatus/typescript#12]
I just upgraded barbatus:typescript to 0.2.2 and barbatus:typescript-compiler to 0.5.1 and now I can't run Meteor. I get a whole slew of errors such as:
`Cannot find name 'Date'`
`Property 'length' does not exist on type 'string[]'.`
`Cannot find name 'Math'`

**Comment by barbatus** [comment]
Does the issue disappear if you switch back to 0.2.1?

**Comment by twastvedt** [comment]
Sorry, should have added that. Yes, it does.

**Comment by barbatus** [comment]
does it happen in a fresh boilerplate Meteor app too?

**Comment by twastvedt** [comment]
Huh. Just tried it on todos-meteor-1.3. Naturally, no difference there.

**Comment by barbatus** [comment]
I just tried fresh todos-meteor-1.3 with 0.2.2. No errors like you have.
Those errors actually mean that the core definition file is not loaded, which is really strange given that you didn't see them before. Try to remove/re-add angular2-compiler, try to remove .meteor/local folder.

**Comment by twastvedt** [comment]
Oh, sorry for the confusion. My latest post was imprecise. I do not see the problem on todos-meteor-1.3 (No difference between old and new versions.) I just removed angular2-compilers from my project, deleted .meteor/local, updated meteor, and then added angular2-compilers. Same problem.

**Comment by jacobdr** [comment]
I can confirm a similar issue. Arose today when I upgraded to Meteor 1.3.1. 

`meteor add barbatus:typescript@=0.2.1` seems to have worked as a temporary fix to the issue

**Comment by barbatus** [comment]
@twastvedt you were right, there was an issue with that, seems for a while already.
Should be fixed in 0.2.3, try meteor update.

**Comment by twastvedt** [comment]
Hmm. I'm still getting the same set of errors on 0.2.3.

**Comment by barbatus** [comment]
Then I need a repo to reproduce

**Comment by barbatus** [comment]
you could also try to remove cache `rm -rf ~/.typescript-cache` and check out after.

**Comment by twastvedt** [comment]
I'm on Windows, and didn't see any sign of such a folder. Where would that be on my machine? I've distilled my project down to a kernel which still throws errors for me: [https://github.com/twastvedt/barbatus-typescript-bug-demo](https://github.com/twastvedt/barbatus-typescript-bug-demo).

**Comment by barbatus** [comment]
There should be `.typescript-cache` folder in in the home dir.
you can try also to change it manually like `TYPESCRIPT_CACHE_DIR=./tscache meteor` and check the issue.

**Comment by twastvedt** [comment]
Well there we go. Removing `~/.typescript-cache` fixed it. Sorry for all the trouble, and thanks for all the help!

**Comment by barbatus** [comment]
it means there is somewhere issue with the cache: it's not invalidated when the package version changes but should. ok, will see how it's gonna go for others.
